anchor_version = "0.30.0"

[toolchain]
anchor_version = "0.30.0"

[features]
resolution = true
skip-lint = false

[programs.mainnet]
token_deployer = "RoCKeTyq1Wf8Co6e2x1RQCC6uxRkZrQ3mDJUEoQryhh"

[programs.devnet]
token_deployer = "RoCKeTyq1Wf8Co6e2x1RQCC6uxRkZrQ3mDJUEoQryhh"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
